# PBS configuration
# If submitting to a different project to your default uncomment line below 
# and change project code as appropriate
project: x77
queue: normal
walltime: 5:00:00
jobname: 025_flux_forced
ncpus: 1455

# Force payu to always find, and save, files in this short (or scratch) project directory
shortpath: /scratch/x77

# Model configuration
model: mom
exe: /scratch/x77/db6174/MoM5/exec/nci/MOM_solo/fms_MOM_solo.x
inputs: 
    - /g/data/ik11/inputs/access-om2/input_20201102/mom_025deg
    - /scratch/x77/db6174/025deg_inputs/flux_forced_3hourly
    - /home/156/db6174/MOM5/025deg_jra55_ryf_flux_forced_3hourly/grid_spec
# Collation
collate:
  walltime: 1:00:00
  mem: 30GB
  ncpus: 4
  queue: express
  exe: /g/data/ik11/inputs/access-om2/bin/mppnccombine

# Misc
runlog: true
stacksize: unlimited
mpirun: --mca orte_base_help_aggregate 0
qsub_flags: -W umask=027
# set number of cores per node (28 for normalbw, 48 for normal on gadi)
platform:
    nodesize: 48

# DANGER! Do not uncomment this without checking the script is synching 
# to the correct location!
# postscript: sync_output_to_gdata.sh
