# PBS configuration
# If submitting to a different project to your default uncomment line below 
# and change project code as appropriate
project: x77

shortpath: /scratch/x77

queue: normal
ncpus: 1455
walltime: 5:00:00
jobname: 025_flux_forced

# Model configuration
model: mom
exe: /scratch/x77/db6174/MoM5/exec/nci/MOM_solo/fms_MOM_solo.x
input:
     - /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg

# Collation
collate:
  restart: true
  walltime: 1:00:00
  mem: 30GB
  ncpus: 4
  queue: express
  exe: /g/data/ik11/inputs/access-om2/bin/mppnccombine

# Misc
runlog: true
stacksize: unlimited
mpirun: --mca orte_base_help_aggregate 0
qsub_flags: -W umask=027
# set number of cores per node (28 for normalbw, 48 for normal on gadi)
platform:
    nodesize: 48

# DANGER! Do not uncomment this without checking the script is synching 
# to the correct location!
# postscript: sync_output_to_gdata.sh
