format: yamanifest
version: 1.0
---
work/accessom2_restart.nml:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_rediGM/restart075/accessom2_restart.nml
  hashes:
    binhash: 60019af0dbab679cb07b828b3e1d7e77
    md5: c7bf87e285863cdc822bc815b5b88f2b
work/ice/RESTART/grid.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_rediGM/restart075/ice/grid.nc
  hashes:
    binhash: 7f41b9e22fa11e6ac548bb41bc73d343
    md5: 24920ffb6c0fea5f6ec1e590a5f46280
work/ice/RESTART/i2o.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_rediGM/restart075/ice/i2o.nc
  hashes:
    binhash: 68258c5f140837e6b3dd9eb91f122711
    md5: 91df2e722f2dffecb706f029b7099155
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_rediGM/restart075/ice/ice.restart_file
  hashes:
    binhash: 64e5fc2e9c75b517f2ea15bbbf4cae2e
    md5: be9664a614bcc960ac50d981c9fcfa18
work/ice/RESTART/iced.2051-01-01-00000.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_rediGM/restart075/ice/iced.2051-01-01-00000.nc
  hashes:
    binhash: 95c0f0449025dc3452853820c0935f16
    md5: 524366d78ddd52f3983cc06fba2e9666
work/ice/RESTART/iced.2052-01-01-00000.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_rediGM/restart075/ice/iced.2052-01-01-00000.nc
  hashes:
    binhash: b9f9d710ff575c0d83119f41d3abb742
    md5: 2a7d93583544f9897452e04a03a3eea0
work/ice/RESTART/kmt.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_rediGM/restart075/ice/kmt.nc
  hashes:
    binhash: 3f33cdcbf36d6091875e30089719b896
    md5: 73d65aaee8da5caa8786963866ddc375
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_rediGM/restart075/ice/mice.nc
  hashes:
    binhash: 5a67601fdc2d172407da79b1aeb3469e
    md5: 81bb9d4ce5524952e10a4233ad1ce912
work/ice/RESTART/monthly_sstsss.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_rediGM/restart075/ice/monthly_sstsss.nc
  hashes:
    binhash: 7f1d9e06f0ca798f5e29936514353781
    md5: 598c7aa8a08fe3f48a621f781dd26331
work/ice/RESTART/o2i.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_rediGM/restart075/ice/o2i.nc
  hashes:
    binhash: cf5e1f5c6e6fdf4d140c51f200735bd9
    md5: 7c77a07537b26159449f3cf052258f75
work/ice/RESTART/sicemass.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_rediGM/restart075/ice/sicemass.nc
  hashes:
    binhash: f0266e87d443433184f0f87c4cc6f5b4
    md5: e8ef4398338187721e8e61e8003675d7
work/ice/RESTART/u_star.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_rediGM/restart075/ice/u_star.nc
  hashes:
    binhash: 067c980084e3ee828be5148107559965
    md5: 8383eaceb08b1706906899cf0296b847
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_rediGM/restart075/ocean/ocean_age.res.nc
  hashes:
    binhash: 237f3530187f3d12321bcb782ee68055
    md5: a916c1d8549e7c029573ea5862ee55f1
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_rediGM/restart075/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 151d3137c52761ed95e4a54c90f36524
    md5: 13de3b0c7894e0b00a3bb98f59cd89f9
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_rediGM/restart075/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: c6c11250d4190e048b0e3f1489c5d956
    md5: f7b87b8f855824e533526e457a6ead9c
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_rediGM/restart075/ocean/ocean_density.res.nc
  hashes:
    binhash: e07c5b5bd5b74248e2bd99c39568f5a5
    md5: 29300bd5c7d8978618f40fabe14eeaee
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_rediGM/restart075/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 6fe67f5ff4f0937a9d6319f9caea2ba5
    md5: aa53c4b774f7a2687085b5a2418221f7
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_rediGM/restart075/ocean/ocean_neutral.res.nc
  hashes:
    binhash: b27b21648e1b1f0e9b03a9ef8c3d8c07
    md5: 58b23cc5e099728ea92aaef27e21f22b
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_rediGM/restart075/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 68204a671eaf07a4a46c63900e313469
    md5: f5bd588eca519f66a085332688609549
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_rediGM/restart075/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f4cd27ca95add21e4a1836be5777d5a5
    md5: 578c428db77f4602913f9b26ff5928d8
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_rediGM/restart075/ocean/ocean_solo.res
  hashes:
    binhash: 5331f89b0c04cec52c30c5bb88a53aca
    md5: 68fd6b8a52f416e37a4c7c5e9b784f93
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_rediGM/restart075/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 826c859bd40fbac4939066a739a807a8
    md5: f149ff2699cbf6608c049b559b027d4c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_rediGM/restart075/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 632a61ef2c8eec4e68c7f77a30d72b77
    md5: db7105e6985b2ebaece20a325b069d48
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_rediGM/restart075/ocean/ocean_tracer.res
  hashes:
    binhash: c92e2a311744152ed6c5b7c69199b757
    md5: 094379d86053fd01f32869550963fd8b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_rediGM/restart075/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 076f38ccb0f2b191235690dcd6170362
    md5: 12a51ef4d6f236062538d8ee8b7ccec7
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_rediGM/restart075/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 59dff612321400e595514799ab3d06bb
    md5: 5ca1d82e9c47046f2d35de8f262a5560
