format: yamanifest
version: 1.0
---
work/accessom2_restart.nml:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart041/accessom2_restart.nml
  hashes:
    binhash: ba50c05ba42b82e43a386de202856215
    md5: 1f7f0f57ac3f86375b1d2433b70fe9ef
work/ice/RESTART/grid.nc:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart041/ice/grid.nc
  hashes:
    binhash: 5e4d2f1b5bfb0157754ea1f81dd09aa0
    md5: 24920ffb6c0fea5f6ec1e590a5f46280
work/ice/RESTART/i2o.nc:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart041/ice/i2o.nc
  hashes:
    binhash: 7535367d5d1c21dafa2012262b0cc19f
    md5: 565f386268b31dfb44c40c4187bedac3
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart041/ice/ice.restart_file
  hashes:
    binhash: d946c9c5124c75b049e744d7ea2539dc
    md5: 5e4d2768aef203093bc38bad17228193
work/ice/RESTART/iced.1983-01-01-00000.nc:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart041/ice/iced.1983-01-01-00000.nc
  hashes:
    binhash: 1ba4e7737f71e7120f2657bb78c99de1
    md5: 9b55dcea4427b68728209e37fe1ff16b
work/ice/RESTART/iced.1984-01-01-00000.nc:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart041/ice/iced.1984-01-01-00000.nc
  hashes:
    binhash: 5ac82a254db44cbffd78830bef27c13d
    md5: 6c3bd8dc123abf42c92d7e3aaf53e39b
work/ice/RESTART/kmt.nc:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart041/ice/kmt.nc
  hashes:
    binhash: 7ffb8d72b920453b9eef7db45ce86dd2
    md5: 73d65aaee8da5caa8786963866ddc375
work/ice/RESTART/monthly_sstsss.nc:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart041/ice/monthly_sstsss.nc
  hashes:
    binhash: ced35abcea22fcecffdce3ee99aa2d22
    md5: 598c7aa8a08fe3f48a621f781dd26331
work/ice/RESTART/o2i.nc:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart041/ice/o2i.nc
  hashes:
    binhash: 0b0b89003ab801ec5c3e1c3d9eda26b0
    md5: 04910bf399a6c754ebff052986b60d3c
work/ice/RESTART/sicemass.nc:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart041/ice/sicemass.nc
  hashes:
    binhash: 0608f3d1bc0d5f102c5383dc46bb7494
    md5: 8825b5735700ceeb4274f5879e28788b
work/ice/RESTART/u_star.nc:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart041/ice/u_star.nc
  hashes:
    binhash: ec9540c5aefe555d2ca240c034b660bc
    md5: a45ac20dffdd836781a903357ccc4447
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart041/ocean/ocean_age.res.nc
  hashes:
    binhash: aa6cb26f7fcbc2714f78a2de6670f90f
    md5: 153c72a82ee8def0c152d514f67cf16c
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart041/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 0a957be23652309ba779844d0824819b
    md5: 993843dcf5f0c3bd213ead54b52e678e
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart041/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 7e69527f7584784ec8178772315c0f7e
    md5: c51f5f8524a523aef1e6c76da5985f98
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart041/ocean/ocean_density.res.nc
  hashes:
    binhash: 892c930251d47e74af23b74df3c15cb6
    md5: edc42584f5b70a09609d8fa9d2ced60d
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart041/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 839ddd71b724865529ed379324080a6d
    md5: a26f9c80c420d966d1b7a00d567f43fa
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart041/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 3f9b0649752efa81c70138f0fa91e14e
    md5: a142db70c01f54bfd13dcac996ac497c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart041/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: a9aac4c8670d7c6fe337a5a37bbd364d
    md5: f8aae0f5bec69f772e97c50a24d9fdb8
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart041/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a393c5f77539ddb66cf63493d4063185
    md5: 3b85c4188b8d6506878a0cbc43c82878
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart041/ocean/ocean_solo.res
  hashes:
    binhash: da06aabf960d410c5da515796c07556e
    md5: 0202d485e4af1cd15525ab6cf9109d49
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart041/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 161e467e74a0db75cee1b5fdb3b75b47
    md5: 1b75e8f2394d7809a5833fd705a1f105
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart041/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e219306ea7eafebe852dba2577b1d92d
    md5: 6e92722ba0794d301ce9cc929b760e64
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart041/ocean/ocean_tracer.res
  hashes:
    binhash: 4966c7c25cdc9c6d9b68bb958e46eda6
    md5: 4f7f016cf08dd42c6ff263cf9a175ece
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart041/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 52320c8afffc68d9b1839b1751858d76
    md5: 1d8fa9257db87b51161ab36c5ab81b6c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart041/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 89173491e573c80ea6bae07f5be79eda
    md5: 23be9e6459dc42fc7211a77bcf1a47e9
