format: yamanifest
version: 1.0
---
work/accessom2_restart.nml:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart035/accessom2_restart.nml
  hashes:
    binhash: 10557f6a65039a36837e6db285927ecc
    md5: f77395e78a252974ef8cab6e435ab137
work/ice/RESTART/grid.nc:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart035/ice/grid.nc
  hashes:
    binhash: 6c0536830e3744ec48c03e9fd0abe63e
    md5: 24920ffb6c0fea5f6ec1e590a5f46280
work/ice/RESTART/i2o.nc:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart035/ice/i2o.nc
  hashes:
    binhash: fa50800ee1174ea090f9f032f7df588a
    md5: 9617e34e592120fec9bab97d5de5d310
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart035/ice/ice.restart_file
  hashes:
    binhash: fbd8ab54d9121110823eb67ae7f16c9d
    md5: c1271b4b293396c7566a52fc14206e0b
work/ice/RESTART/iced.1971-01-01-00000.nc:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart035/ice/iced.1971-01-01-00000.nc
  hashes:
    binhash: 88a21c28b3f884b95ea82dfd4b749b90
    md5: c597f93b58ab5bbbf45edb4390431681
work/ice/RESTART/iced.1972-01-01-00000.nc:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart035/ice/iced.1972-01-01-00000.nc
  hashes:
    binhash: 75ff6a120c7054623e82d546f2f19ac6
    md5: ea10b2e106b2f9942286fb9817fd8ec4
work/ice/RESTART/kmt.nc:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart035/ice/kmt.nc
  hashes:
    binhash: 63b2f14569723c87af9f1c7702bd9bff
    md5: 73d65aaee8da5caa8786963866ddc375
work/ice/RESTART/monthly_sstsss.nc:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart035/ice/monthly_sstsss.nc
  hashes:
    binhash: bdaca9a3291047f39edab3be5d380a5d
    md5: 598c7aa8a08fe3f48a621f781dd26331
work/ice/RESTART/o2i.nc:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart035/ice/o2i.nc
  hashes:
    binhash: 552b4d684300d17f0602cf5764044129
    md5: 405a8f82cf0152b3a5b6aff109de3521
work/ice/RESTART/sicemass.nc:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart035/ice/sicemass.nc
  hashes:
    binhash: 582c6f5023ba00ab61827c91f0f317b5
    md5: e75d499e0cea5ec1e628bebe28168426
work/ice/RESTART/u_star.nc:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart035/ice/u_star.nc
  hashes:
    binhash: 13bfbd638c66bc1c7656da9bd754e780
    md5: c97a4a09bd00648cc2370b62be935e89
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart035/ocean/ocean_age.res.nc
  hashes:
    binhash: bb75cde395e82230c6aabbc14d01c18d
    md5: 67792ffbc5ceaf80eaf4bd47adde544a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart035/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: acb60afd62093c3f1fb231f6944c6c58
    md5: a7ebd242189914be8a5cc19e1fbc83bd
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart035/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 311f73fbf66a9379f86bb40c0de52a3f
    md5: bc76361e388801851c287e3ae262024e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart035/ocean/ocean_density.res.nc
  hashes:
    binhash: 0c65886659159674afda134cbddbaa28
    md5: 0a18c6c26455c1f0b74c65353157f0dd
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart035/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 23be18bcdc5fe47078b4d9b2aec2f5d4
    md5: 287fed5f407f4a79f9fce5c92b55b373
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart035/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 08f583816de72970623f0f8c69f7ef5c
    md5: a14caeabfe237ca9d7b2973c034e3a95
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart035/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 21fc939dd8006d2829b9a152f9f9ddfa
    md5: f3012bc6088e17a384fcd60dc875a4d0
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart035/ocean/ocean_sbc.res.nc
  hashes:
    binhash: deb7f3a6b7352d66027360fdb2bbd070
    md5: 8c66f4397122b97c495b1c2a82039ef7
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart035/ocean/ocean_solo.res
  hashes:
    binhash: ea8975d5bc46f38fa4f7ce90aa547904
    md5: 0d85624656c8034a0d243f2458383782
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart035/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 38976dc9d46da1a7ff67437355558b38
    md5: b551481d7dde4f4efbef1b1f39138a03
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart035/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 8379ed11c7f52df8fae6960ad27eec02
    md5: aed8c51948aace97860b531696fd76dc
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart035/ocean/ocean_tracer.res
  hashes:
    binhash: faaf5290e8b9e3208629f8f741887e66
    md5: 3730baf8113f67db2786a3429cc2d8d6
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart035/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 930206e2dab5e4f30c80e10a16408760
    md5: 87df6e34c7237b5cef64021526c96c36
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart035/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 022101b8c12dbd5e4ca7640ccdb46f26
    md5: 3467841ecde824ad99694c48e97c99c6
