format: yamanifest
version: 1.0
---
work/accessom2_restart.nml:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart026/accessom2_restart.nml
  hashes:
    binhash: 6ebd0fc9b27bcae46f5a91114cb60a9a
    md5: ae3b95f623333f7c3b85b46a1af4fda8
work/ice/RESTART/grid.nc:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart026/ice/grid.nc
  hashes:
    binhash: 24526d27f4db298890c4c9f574ae8dea
    md5: 24920ffb6c0fea5f6ec1e590a5f46280
work/ice/RESTART/i2o.nc:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart026/ice/i2o.nc
  hashes:
    binhash: 5e0a4c03f11651c56ffa980c6be7643f
    md5: 13bb39f46bebdd19d20deaf6266fbdfd
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart026/ice/ice.restart_file
  hashes:
    binhash: 2cb5c091b6e4b5a41a9e5ea6e40a893e
    md5: 4b129e6ed223e92a06f33648be6d8465
work/ice/RESTART/iced.1953-01-01-00000.nc:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart026/ice/iced.1953-01-01-00000.nc
  hashes:
    binhash: af07d29c57c505ed894b9da5e004be5f
    md5: 9548755e80b7e0266ac5869b22b855ca
work/ice/RESTART/iced.1954-01-01-00000.nc:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart026/ice/iced.1954-01-01-00000.nc
  hashes:
    binhash: f6bed7c699355f6c8963e1d78781d9be
    md5: d1af1cc9cf5b6180ed434f46a0d34828
work/ice/RESTART/kmt.nc:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart026/ice/kmt.nc
  hashes:
    binhash: aeb1a7a1945522e2b944e4e4defcb9b3
    md5: 73d65aaee8da5caa8786963866ddc375
work/ice/RESTART/monthly_sstsss.nc:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart026/ice/monthly_sstsss.nc
  hashes:
    binhash: 7c64043c81d2c57a0062f7d7da31145e
    md5: 598c7aa8a08fe3f48a621f781dd26331
work/ice/RESTART/o2i.nc:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart026/ice/o2i.nc
  hashes:
    binhash: 52b93a1adadc1612d2838a7d5829ec92
    md5: c126845c6078919373bffb03894b3fa4
work/ice/RESTART/sicemass.nc:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart026/ice/sicemass.nc
  hashes:
    binhash: 1bacf4a5b33ec9e6e74062010f3b9d12
    md5: b126b81298875a246998b70b558fdfc0
work/ice/RESTART/u_star.nc:
  copy: true
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart026/ice/u_star.nc
  hashes:
    binhash: 74c4713a05c9df80624c8412b6fa3af9
    md5: 624977e84b66b13cba2fb7a0cd2953d5
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart026/ocean/ocean_age.res.nc
  hashes:
    binhash: d42393e2c5fa0e19259e539f7d29cfb4
    md5: cb0295a12bb629f1f11787779680671f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart026/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: f47a68e2ce81f0ce889123a5c294c06c
    md5: 53b6f6d3d40c789af9506c5f5d1091d2
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart026/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 240f628106da3a563a896c6fa0a05f7d
    md5: 21dfec2173313b45cf70d25f8409ac72
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart026/ocean/ocean_density.res.nc
  hashes:
    binhash: 597ee8cdd9ed606c27103668eccc39d3
    md5: 9b98b001e4ebf3bc295cc9ec6d3ff69e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart026/ocean/ocean_frazil.res.nc
  hashes:
    binhash: cb4681fca1b8fcbc03f2772975e8715a
    md5: a9ac19329de936670c4bda4cb4a1f84e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart026/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 5511ec9254017d584fd265422f4e9bef
    md5: 92f914cdd31c22d774939bc0cd1cd3ce
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart026/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d68aa8dc511f2ed3caa6e5a2919eccf5
    md5: 52fd2a4ce7926f252626d0d6ed1c7118
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart026/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4f24292340d2090bafecbfd8df05f657
    md5: fcc66f2012efd79796984a384029cfe9
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart026/ocean/ocean_solo.res
  hashes:
    binhash: b771f49f7e57609672b89a8e0219b956
    md5: e707ac7887d0a08365cb62a14249d025
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart026/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 022b4a9383b39872bba81d9ff84d4f15
    md5: 286e252f3a487cc1b4a8a2cc0ea711fc
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart026/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 3a8a5d48213e4b9fed81148b8b1ecd57
    md5: 8aa6856e2f627625e79c5ad4a9363e04
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart026/ocean/ocean_tracer.res
  hashes:
    binhash: 3ebc170166a60355969ee7e7722c9444
    md5: a1e03e6ef6535a73ac0ca962164f5198
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart026/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c2bea6ecd5c8e1686b514e294a4c96d3
    md5: a90003768a51ae3b43866d95769cd321
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/x77/db6174/access-om2/archive/025deg_jra55_ryf_param_kpp3/restart026/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 084d710791a2f4043cf995d04bff43d9
    md5: d26d88624ffa29afae8cd7455e1c48ce
